
services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tour_planner
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./tour-planner-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tour_planner;Username=postgres;Password=password
    depends_on:
      - db

  frontend:
    build:
      context: ./tour-planner-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
